# Generated by Django 5.2.8 on 2025-11-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
