# Generated by Django 5.2.8 on 2025-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_sellerprofile_bank_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
