# Generated by Django 5.2.8 on 2025-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
    ]
