# Generated by Django 5.2.8 on 2025-11-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_sellerprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='firebase_uid',
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=32),
        ),
    ]
