# Generated by Django 5.2.8 on 2025-11-17 10:19

import cloudinary_storage.storage
import sellers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=sellers.models.seller_doc_path),
        ),
    ]
